### ISSUE TITLE
Termux login


### ISSUE THREAD

**Issue by kumar901** [htr-tech/htr-tech#3]
I installed termux login using htr tech 
But now it showing this ![Screenshot_2020-12-30-14-56-01-648_com.termux.jpg](https://user-images.githubusercontent.com/76768385/103342296-270fa100-4aaf-11eb-9801-2000f9070ee7.jpg)
Help me out with this

**Comment by Mayur8291** [comment]
Same issue occurs to me also

**Comment by htr-tech** [comment]
remove it from `$PREFIX/etc/bash.bashrc`
