### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by arifdere** [htr-tech/htr-tech#6]
hello

**Comment by htr-tech** [comment]
sup 👋

**Comment by arifdere** [comment]
bro do you speak turkish

7 Nis 2022 Per 11:29 tarihinde Tahmid Rayat ***@***.***> şunu
yazdı:

**Comment by arifdere** [comment]
bro do you speak turkish

**Comment by htr-tech** [comment]
no bro ...😢

**Comment by arifdere** [comment]
türkçe konuşalım


8 Nis 2022 Cum 18:20 tarihinde Tahmid Rayat ***@***.***> şunu
yazdı:

**Comment by htr-tech** [comment]
huh ?
